#!/bin/sh 

cd /tmp

wget -q www.celestrak.com/NORAD/elements/amateur.txt -O amateur.txt 
wget -q www.celestrak.com/NORAD/elements/visual.txt -O visual.txt 
wget -q www.celestrak.com/NORAD/elements/weather.txt -O weather.txt 
/usr/local/bin/predict -u amateur.txt visual.txt weather.txt
